# 端口
server:
  port: ${SERVER_PORT:5354}

com:
  gitee:
    swsk33:
      # SensorThings服务端配置
      sensor-things-server:
        # HTTP API配置
        host: ${SENSOR_THINGS_HTTP_HOST:127.0.0.1}
        port: ${SENSOR_THINGS_HTTP_PORT:8080}
        # MQTT Broker配置
        mqtt-broker-host: ${SENSOR_THINGS_MQTT_HOST:127.0.0.1}
        mqtt-broker-port: ${SENSOR_THINGS_MQTT_PORT:1883}